### PR TITLE
Namespaced version

### PR DESCRIPTION
**Pull request by adrianbj**

### CODE REVIEW

**Comment by adrianbj** [comment]
@Toutouwai - I have pushed that latest version (with a change to `includeOnce` and making all core actions namespaced) live. I did come across one issue though - I noticed that you had commented out a namespace declaration in one of your custom actions and that caused `getNamespace()` to still return the namespace and break the action. I have reported here (https://github.com/processwire/processwire-issues/issues/1878) but you will need to modify any actions with commented namespaces until that is fixed.

**Comment by Toutouwai** [comment]
Thanks, I noticed that too and it's no problem for me to change that at my end. I'll be wanting to add the namespace to all my custom actions anyway.

**Comment by Toutouwai** [comment]
And a big thanks for making this update to the module!

**Comment by adrianbj** [comment]
> And a big thanks for making this update to the module!

No worries, thanks for your help getting it dialed.

**Pull request merged**
